In [22]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [23]:
df = pd.read_csv('with-user-id-center.csv')

In [24]:
df.columns

Index(['Unnamed: 0', 'userid', 'lat', 'lng', 'centers'], dtype='object')

In [25]:
df.head(3)

Unnamed: 0  userid        lat        lng  centers
0      958713    4466  38.952334 -77.447948        3
1      444404    1544  39.763549 -86.331929       45
2      763759    3252  42.051870 -70.185600       12

In [26]:
X = df[['lat', 'lng']]
y = df['centers']

In [27]:
from sklearn.model_selection import train_test_split


In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [29]:
from sklearn.neighbors import KNeighborsClassifier

In [30]:
knn = KNeighborsClassifier()

In [31]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [32]:
knn.score(X_test, y_test)

0.9980493514093436

In [33]:
knn.predict([[42.267552,-114.432897]])

array([30], dtype=int64)

In [34]:
df[df['centers']==30]['userid'].unique()

array([ 185,  360, 2276, 2277,  567, 4088, 2075, 3730, 3411, 3049, 2164,
       1921, 3329, 3541, 2488, 3240, 1662, 2548, 3251, 2494, 3351, 3438,
       4632, 2744, 1122, 3462, 2734, 4302, 4748, 2305,  633, 3075, 2835,
       2001, 2590, 2566, 2421, 2310, 1114, 1867,  583, 1618,  458, 3418,
       2483, 4669, 1523, 1839, 1309, 2056, 4503,  138, 4093,  908, 3395,
       3144, 3964, 1174, 3558,  498,  752, 2547, 2620, 4242, 1146, 3087,
        661, 4445, 4352,  745, 1014, 1891, 2960, 4366, 3769, 2856, 2350,
       2194, 4371, 2151, 1007, 4363, 2866, 3303, 3488, 3373, 4151, 3234],
      dtype=int64)

In [35]:
from sklearn.tree import DecisionTreeClassifier

In [36]:
dt = DecisionTreeClassifier()

In [37]:
dt.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [38]:
dt.score(X_test, y_test)

0.9980493514093436

In [39]:
dt.predict([[42.267552,-114.432897]])

array([30], dtype=int64)

In [ ]:
def get_model():
    models = [D]