In [3]:
import numpy as np

### From Python list

In [4]:
my_list = [4,6,3,6,9]
my_list

[4, 6, 3, 6, 9]

In [5]:
arr = np.array(my_list)
arr

array([4, 6, 3, 6, 9])

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
arr = np.array(my_matrix)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [12]:
np.arange(3,20, 5)

array([ 3,  8, 13, 18])

### zeros and ones

Generate arrays of zeros or ones

In [13]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

### linspace
Return evenly spaced numbers over a specified interval.

In [16]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

## eye

Creates an identity matrix

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [18]:
np.random.rand(3)

array([0.35443158, 0.002846  , 0.28952871])

In [19]:
np.random.rand(5,5)

array([[0.03780038, 0.79781169, 0.93052406, 0.67018659, 0.02675726],
       [0.88795723, 0.90974322, 0.27046795, 0.7990365 , 0.14356067],
       [0.32504503, 0.75172379, 0.71154452, 0.17610255, 0.4731705 ],
       [0.78928389, 0.05808988, 0.67581237, 0.62017055, 0.11807555],
       [0.40842232, 0.06914569, 0.04087632, 0.20193212, 0.56631358]])

In [22]:
a  = np.random.rand(3,5)
a.shape

(3, 5)

In [23]:
a

array([[0.28074577, 0.69693698, 0.55494197, 0.36636948, 0.74311884],
       [0.18379342, 0.78356215, 0.31835638, 0.37914971, 0.94197321],
       [0.15967074, 0.04524002, 0.96090992, 0.74521393, 0.28675184]])

In [26]:
np.random.rand(3,5).shape

(3, 5)

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [24]:
np.random.randn(2)

array([ 0.0951769 , -0.07423172])

In [25]:
np.random.randn(5,5)

array([[-2.03693317,  1.05969865, -1.08998983,  1.36700086, -0.69162157],
       [ 0.28085363,  0.18984   , -0.00969952,  0.72988116, -0.82033404],
       [ 1.53536807,  2.43724106,  0.11597558,  1.55343003, -0.43710443],
       [-0.56265755, -1.02776697,  2.00511028, -1.59448665,  0.6035767 ],
       [ 1.21521783,  1.10729712,  0.49770322, -0.13578915,  0.72449509]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [27]:
np.random.randint(1,100)

52

In [28]:
np.random.randint(1,100,10)

array([90, 95, 41, 58, 80, 11, 71, 60, 90, 37])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [29]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
ranarr

array([23, 28, 24, 15, 12, 23,  9, 32, 28,  3])

## Reshape
Returns an array containing the same data with a new shape.
.reshape(...) . But the number of items should remain the same

In [36]:
arr.shape

(25,)

In [34]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
np.random.rand(1,200).reshape(10,20)

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [40]:
ranarr

array([23, 28, 24, 15, 12, 23,  9, 32, 28,  3])

In [45]:
ranarr.max(), np.max(ranarr)

(32, 32)

In [46]:
ranarr.min(), np.min(ranarr)

(3, 3)

In [47]:
ranarr.mean(), np.mean(ranarr)

(19.7, 19.7)

In [48]:
ranarr.sum(), np.sum(ranarr)

(197, 197)

### dtype

You can also grab the data type of the object in the array:
arr.dtype

In [49]:
ranarr.dtype

dtype('int32')