# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [1]:
import numpy as np
arr = np.arange(0,10)

- Addition and subtraction of two arrays arr + arr and arr - arr
- Multiplication of two arrays arr * arr
- Division of two arrays - Note: Gives a warning on division by zero rather than an error

In [3]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
arr * .2 + arr

array([ 0. ,  1.2,  2.4,  3.6,  4.8,  6. ,  7.2,  8.4,  9.6, 10.8])

In [7]:
arr = arr + arr

In [8]:
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
arr/arr

D:\sw\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [11]:
1/arr

D:\sw\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 0.5       , 0.25      , 0.16666667, 0.125     ,
       0.1       , 0.08333333, 0.07142857, 0.0625    , 0.05555556])

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

- square root using np.sqrt
- exp e^ using np.exp
- max using np.max or can use arr.max() also


In [12]:
np.sqrt(arr)

array([0.        , 1.41421356, 2.        , 2.44948974, 2.82842712,
       3.16227766, 3.46410162, 3.74165739, 4.        , 4.24264069])

In [13]:
np.exp(arr)

array([1.00000000e+00, 7.38905610e+00, 5.45981500e+01, 4.03428793e+02,
       2.98095799e+03, 2.20264658e+04, 1.62754791e+05, 1.20260428e+06,
       8.88611052e+06, 6.56599691e+07])