# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [2]:
#Creating sample array
arr = np.arange(0,11)

In [3]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

- Get a value at an index

In [4]:
arr[4]

4

- Get a value in a range

In [8]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[4:9]

array([4, 5, 6, 7, 8])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

- Set a value with index range broad cast a value.
- a[0:5] = 300

In [10]:
arr[0:5] =20

In [11]:
arr

array([20, 20, 20, 20, 20,  5,  6,  7,  8,  9, 10])

In [12]:
arr[:] = 50

In [13]:
arr

array([50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [16]:
ft = np.arange(50).reshape(5,10)

In [17]:
ft

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [20]:
ft[2][4], ft[2,4]

(24, 24)

In [21]:
ft[2:,3:]

array([[23, 24, 25, 26, 27, 28, 29],
       [33, 34, 35, 36, 37, 38, 39],
       [43, 44, 45, 46, 47, 48, 49]])

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [22]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [24]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [28]:
arr[arr < arr.mean()] 

array([1, 2, 3, 4, 5])

In [40]:
len(arr[arr > arr.mean()])

5

In [43]:
sum(arr > arr.mean())

5

In [9]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [10]:
bool_arr = arr>4

In [11]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [12]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [13]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
np.arange(10).shape

(10,)

In [30]:
np.arange(10).reshape(1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [32]:
np.arange(10).reshape(1,10).shape

(1, 10)