In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

- load diabetes data set

In [2]:
df = pd.read_csv('diabetes_data_train_710samples.csv')

- select features and target

In [4]:
df.head()

Row  preg_count  glucose_concentration  diastolic_bp  \
0    0           6                    148            72   
1    1           1                     85            66   
2    2           8                    183            64   
3    3           1                     89            66   
4    4           0                    137            40   

   triceps_skin_fold_thickness  two_hr_serum_insulin   bmi  diabetes_pedi  \
0                           35                     0  33.6          0.627   
1                           29                     0  26.6          0.351   
2                            0                     0  23.3          0.672   
3                           23                    94  28.1          0.167   
4                           35                   168  43.1          2.288   

   age  diabetes_class  
0   50               1  
1   31               0  
2   32               1  
3   21               0  
4   33               1

In [6]:
df.columns

Index(['Row', 'preg_count', 'glucose_concentration', 'diastolic_bp',
       'triceps_skin_fold_thickness', 'two_hr_serum_insulin', 'bmi',
       'diabetes_pedi', 'age', 'diabetes_class'],
      dtype='object')

In [8]:
df.corr()['diabetes_class']

Row                           -0.063441
preg_count                     0.230506
glucose_concentration          0.458086
diastolic_bp                   0.058391
triceps_skin_fold_thickness    0.084880
two_hr_serum_insulin           0.137614
bmi                            0.291296
diabetes_pedi                  0.172729
age                            0.231088
diabetes_class                 1.000000
Name: diabetes_class, dtype: float64

In [10]:
df.drop('Row', axis=1, inplace=True)

In [9]:
X = df[['preg_count', 'glucose_concentration', 'diastolic_bp',
       'triceps_skin_fold_thickness', 'two_hr_serum_insulin', 'bmi',
       'diabetes_pedi', 'age']]
y = df['diabetes_class']

- split the data set

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=101)

- import LogisticRegression from sklearn.linear_model
- create an object
- fit

In [76]:
from sklearn.linear_model import LogisticRegression
logr = LogisticRegression()
logr.fit(X_train, y_train)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [71]:
logr.n_iter_

array([18], dtype=int32)

- predict the value

In [62]:
y_pred = logr.predict(X_test)

In [16]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1], dtype=int64)

In [19]:
sum(y_test == y_pred)/ len(y_test)

0.755868544600939

In [68]:
logr.score(X_test, y_test)

0.7323943661971831

In [21]:
sum(df['diabetes_class'] == 0)/len(df)

0.6535211267605634

- metrics for LR  - lr.score(X_test, y_test)

In [22]:
from sklearn.metrics import confusion_matrix

In [26]:
tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
tn, fp, fn, tp

(119, 18, 34, 42)

In [27]:
y_prob = logr.predict_proba(X_test)

In [43]:
y_prob_pred = [ 0 if y[1] <= 0.35 else 1 for y in  y_prob]

In [44]:
tn, fp, fn, tp = confusion_matrix(y_test, y_prob_pred).ravel()
tn,fp,fn,tp

(97, 40, 18, 58)

In [ ]:
logr.predict_proba()

In [46]:
(129 + 30) / len(X_test)

0.7464788732394366

- another metric confusion matrix 
- import confustion_matrix from sklearn.metrics
- tn, fp, fn, tp

In [ ]:
logr.predict_proba()

In [47]:
logr.predict_proba([[6,148,72,35,0,33.6,0.627,50]])

array([[0.35076642, 0.64923358]])

In [48]:
logr.predict([[6,148,72,35,0,33.6,0.627,50]])

array([1], dtype=int64)

- change threshold by running predict_proba instead of predict

In [49]:
import pickle

In [50]:
fh = open('diab.pkl', 'wb')

In [53]:
logr.classes_

array([0, 1], dtype=int64)

In [51]:
pickle.dump(logr, fh)

In [54]:
logr.coef_

array([[ 1.08255884e-01,  2.65746916e-02, -1.64993845e-02,
         2.17468908e-03, -6.66851663e-04,  4.51539755e-02,
         7.31051069e-01,  9.16850278e-03]])

In [52]:
fh.close()

In [77]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [78]:
knn.score(X_test, y_test)

0.6619718309859155